#if defined(TARGET_NUMAKER_PFM_NUC472)

#define MBEDTLS_DES_C

#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C

#define MBEDTLS_AES_C

#if ! defined(MBEDTLS_CONFIG_HW_SUPPORT)

#define MBEDTLS_DES_ALT

#define MBEDTLS_SHA1_ALT
#define MBEDTLS_SHA256_ALT

#define MBEDTLS_AES_ALT
#define MBEDTLS_AES_SETKEY_ENC_ALT
#define MBEDTLS_AES_SETKEY_DEC_ALT
#define MBEDTLS_AES_ENCRYPT_ALT
#define MBEDTLS_AES_DECRYPT_ALT

#endif

#elif defined(TARGET_NUMAKER_PFM_M487)

#define MBEDTLS_DES_C

#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA512_C

#define MBEDTLS_AES_C

#if ! defined(MBEDTLS_CONFIG_HW_SUPPORT)

#define MBEDTLS_DES_ALT

#define MBEDTLS_SHA1_ALT
#define MBEDTLS_SHA256_ALT
#define MBEDTLS_SHA512_ALT

#define MBEDTLS_AES_ALT
#define MBEDTLS_AES_SETKEY_ENC_ALT
#define MBEDTLS_AES_SETKEY_DEC_ALT
#define MBEDTLS_AES_ENCRYPT_ALT
#define MBEDTLS_AES_DECRYPT_ALT

#endif

#endif
