#if defined(TARGET_NUMAKER_PFM_NUC472)

#define MBEDTLS_DES_C

#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C

#define MBEDTLS_AES_C

#elif defined(TARGET_NUMAKER_PFM_M487)

#define MBEDTLS_DES_C

#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA512_C

#define MBEDTLS_AES_C

#endif
